package service.model

import org.joda.time.DateTime
import service.model.FuelType._

/**
 * Project: rest-ads
 * Package: service.model
 * Created by asoloviov on 6/27/17 3:07 PM.
 */
case class ADEntity(id: Option[Long], title: String, fuel: FuelType, price: Int, `new`: Boolean, mileage: Option[Int] = None, firstRegistration: Option[DateTime] = None) {
  //TODO move to UUID type of id field (note it will be used in URI path, i.e encoded, and generated by the DB during entity creation)
  require(!title.isEmpty, "title.field.empty")
  require(`new` == mileage.isEmpty, "new.car.mileage.defined")
  require(`new` == firstRegistration.isEmpty, "new.car.firstRegistration.defined")
  def withID(thatID: Long): ADEntity = copy(id = Some(thatID))
  def idDefined: Boolean = id.isDefined
}

object ADEntity {

  import service.utils.JodaDateTimeExtensions._
  import spray.json.DefaultJsonProtocol._

  implicit class entityAD2UpdateAD(val ad: ADEntity) extends AnyVal {
    def toUpdateAD: ADEntityUpdate = ADEntityUpdate(Some(ad.title), Some(ad.fuel), Some(ad.price), Some(ad.`new`), ad.mileage, ad.firstRegistration)
  }

  implicit val adEntityFormat = jsonFormat7(ADEntity.apply)
}
