package service.model

import org.joda.time.DateTime
import service.model.FuelType._

/**
 * Project: rest-ads
 * Package: service.model
 * Created by asoloviov on 6/27/17 3:07 PM.
 */
case class ADEntity(id: Long, title: String, fuel: FuelType, price: Int, `new`: Boolean, mileage: Option[Int] = None, firstRegistration: Option[DateTime] = None) {
//TODO move to UUID type of id field (note it will be used in URI path, i.e encoded, and generated by the DB during entity creation)
  require(!title.isEmpty, "title.empty")
  require(`new` == mileage.isEmpty, "new.car.mileage.defined")
  require(`new` == firstRegistration.isEmpty, "new.car.firstRegistration.defined")
}

object ADEntity {

  import service.utils.JodaDateTimeExtensions._
  import spray.json.DefaultJsonProtocol._

  implicit val adEntityFormat = jsonFormat7(ADEntity.apply)
}
